### ISSUE TITLE
Embedded needed DLLs in output exe file

### ISSUE THREAD

**Issue by matrixik** [visualfc/go-iup#1]
Hello,
thank you for maintaining go-iup.

I'm completely new to Go programming and I would like to know if it's possible to embed Iup DLLs into output exe file when source is compiled?

Best regards

**Comment by visualfc** [comment]
2012/10/19 Dobrosław Żybort notifications@github.com

> Hello,
> thank you for maintaining go-iup.
> 
> I'm completely new to Go programming and I would like to know if it's
> possible to embed Iup DLLs into output exe file when source is compiled?
> 
> Best regards
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/visualfc/go-iup/issues/1.

I'm try, but not success

**Comment by matrixik** [comment]
Too bad, but thank you for your efforts.

Best regards

**Comment by matrixik** [comment]
Not perfect but working and free:
http://en.wikipedia.org/wiki/IExpress
How to:
http://www.mpgh.net/forum/33-visual-basic-programming/143392-tut-how-merge-exes-dlls-without-ilmerge.html#post1924248

Best regards

**Comment by matrixik** [comment]
Another one, also not perfect but can be run from batch file:
http://geeklad.com/convert-to-exe-with-free-program

Example demo (go-iup\examples\demo):
http://www.mediafire.com/download.php?vitxow5s966k55o
Run with `build.bat` file

Best regards

**Comment by matrixik** [comment]
One more thing **Cameyo ZeroInstaller** (free application virtualization,
ZeroInstaller is `command-line generator of virtual applications`, beta)
http://www.cameyo.com/zero/index.html

Sample for `hello` example:
http://www.mediafire.com/download.php?vitxow5s966k55o
Run `ZeroInstaller\ZeroInstaller.exe Hello.xml`

Best regards

**Comment by matrixik** [comment]
Enigma Virtual Box (freeware):
http://enigmaprotector.com/en/aboutvb.html

Nice but can't build exe with command line.

**Comment by matrixik** [comment]
Or Enigma Virtual Box have command line tool:
http://forum.enigmaprotector.com/viewtopic.php?p=8719#p8719

`enigmavbconsole.exe test.evb`
